//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminView.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdminView.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nazwisko,imie,miejscowosc,data_urodzenia,kategoria,rower,nazwa_dystansu,czas_przejazdu,msc_open_csv,msc_kat_csv,liczba_pomiarow,pomiary_csv
        ///Ważny,Adam,,1984,M30 M30,,M30,,,,0,
        ///KALODZITSA,ALIAKSANDR,,1960,M50 M50,,M50,,,,0,
        ///Barwiński DNF,Wiktor DNF,,2001,M20 JUNIOR,,M20,,,,0,
        ///Kaźmierczak,Barbara,Zgierz,1985-03-12,AMAT AMATOR,,AMAT,,,,0,
        ///Michalak,Łukasz,Pabianice,1985-04-07,M30 M30,,M30,,,,0,
        ///CZECHOWSKI,TOMASZ,Ksawerów,1986-01-10,M30 M30,,M30,,,,0,
        ///Podwysocki,Bartłomiej,łódź,1984-03-14,AMAT AMATOR,,AMA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Aleksandrow {
            get {
                return ResourceManager.GetString("Aleksandrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nazwisko,imie,miejscowosc,data_urodzenia,kategoria,rower,nazwa_dystansu,czas_przejazdu,msc_open_csv,msc_kat_csv,liczba_pomiarow,pomiary_csv
        ///Studziński DNS,Adam DNS,,1982,120 M30,,120,,,,0,
        ///Musiałowski DNS,Piotr DNS,,1977,90 M40,,90,,,,0,
        ///Polowczyk,Jarosław,Zduńskawola,1972-06-30,60 AMATOR,,60,,,,0,
        ///Jóźwiak DNS,Cezary DNS,,1973,90 M40,,90,,,,0,
        ///Władczyk,Zdzisław,Łódź,1954-09-14,60 M60,,60,,,,0,
        ///Ważny DNS,Adam DNS,,1984,120 M30,,120,,,,0,
        ///Malinowski DNS,Kamil DNS,Pabianice,1980-09-23,120 M30,,120,,,,0, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Zdunska {
            get {
                return ResourceManager.GetString("Zdunska", resourceCulture);
            }
        }
    }
}
