//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseCoreTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BaseCoreTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id_z;nr_startowy;imie;nazwisko;miejscowosc;klub;data_urodzenia;plec;rower;distanceId;czas_startu;kategoria;kat_wiek;nr_grupy;nazwa_dystansu;dlugosc
        ///0;214;Jacek;Lipowski;Pabianice;;1965-07-01;M;inny;;10:58:00;MINI M5i;M5;;MINI;73
        ///0;523;LENA;ŚNIEG;ŁASK;;1966-05-22;K;inny;;11:46:00;+ROD K5i;K5;;+RODZINNY;36
        ///0;450;Krzysztof;Czuba;Śliwniki;;1971-04-14;M;szosowy;;11:42:00;MINI M4s;M4;;MINI;73
        ///0;519;LESZEK;ROJEWSKI;ŁASK;;1967-06-23;M;inny;;11:46:00;+ROD M4i;M4;;+RODZINNY;36
        ///0;531;Michał;Paluch;Łask;Amator;200 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Players {
            get {
                return ResourceManager.GetString("Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to num;rfid;time;antenna;
        ///630;2000FA4727F2690004EC;09:48:20.197;1
        ///129;2000FA4727F269000101;09:48:23.687;1
        ///129;2000FA4727F269000102;09:48:23.772;1
        ///83;2000FA4727F2690000A6;09:48:24.577;1
        ///13;2000FA4727F26900001A;09:48:31.557;3
        ///13;2000FA4727F269000019;09:48:31.667;1
        ///14;2000FA4727F26900001C;09:48:32.172;3
        ///17;2000FA4727F269000022;09:48:32.642;1
        ///17;2000FA4727F269000021;09:48:32.657;1
        ///12;2000FA4727F269000017;09:48:32.832;3
        ///12;2000FA4727F269000018;09:48:32.842;3
        ///630;2000FA4727F2690004EC;09:49:22.117;1
        ///630; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Times {
            get {
                return ResourceManager.GetString("Times", resourceCulture);
            }
        }
    }
}
